name: Detect Changed Terraform Module

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  detect-module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect Changed Module
        id: detect
        shell: bash
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD

          MODULE=$(git diff --name-only HEAD^ HEAD \
            | cut -d'/' -f1 \
            | sort -u \
            | grep -E '^(eks|terraform-rds|vpc-modules)$' \
            | head -1)

          echo "MODULE=$MODULE"

          echo "module=$MODULE" >> "$GITHUB_OUTPUT"

      - name: Print Module
        run: |
          echo "Changed Module = ${{ steps.detect.outputs.module }}"